# Generated by Django 6.0.3 on 2026-03-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_horario_hora_fim_alter_horario_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
