# Generated by Django 6.0.3 on 2026-03-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_agendamento_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='ativo',
        ),
    ]
