# Generated by Django 6.0.3 on 2026-03-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='quadra_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='quadra_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.horario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='quadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.quadra'),
        ),
    ]
