# Generated by Django 6.0.3 on 2026-03-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_agendamento_hora_fim_agendamento_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
