# Generated by Django 6.0.3 on 2026-03-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_agendamento_pago_agendamento_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='payment_id',
        ),
    ]
