# Generated by Django 6.0.3 on 2026-03-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_agendamento_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', models.JSONField(blank=True, null=True)),
                ('datas', models.JSONField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
