# Generated by Django 6.0.3 on 2026-03-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_descanso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descanso',
            name='datas',
        ),
        migrations.RemoveField(
            model_name='descanso',
            name='motivo',
        ),
    ]
